/// Mock product data for demo / presentation purposes.
/// No DB required — all data is hardcoded here.
library;

import 'product_model.dart';

// ── Mock image helper ─────────────────────────────────────
// Uses picsum.photos with a seed so images are consistent across loads.
ProductImage _img(String productId, String seed) => ProductImage(
      id: 'mock-img-$seed',
      productId: productId,
      imagePath: 'https://picsum.photos/seed/$seed/400/400',
      isPrimary: true,
      sortOrder: 0,
    );

// ── Mock products ─────────────────────────────────────────
final List<Product> mockProducts = [
  Product(
    id: 'mock-1',
    sellerId: 'mock-seller',
    categoryId: 'cat-electro',
    categoryName: 'Electrónica',
    title: 'iPhone 13 Pro 128GB – Grafito',
    description:
        'Excelente estado. Batería al 94%, sin rayones. Incluye cargador original y caja. Desbloqueado para cualquier operadora.',
    price: 380.00,
    isNegotiable: true,
    condition: ProductCondition.comoNuevo,
    status: ProductStatus.active,
    brand: 'Apple',
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    updatedAt: DateTime.now(),
    sellerName: 'Carlos M.',
    sellerTrustScore: 92,
    images: [_img('mock-1', 'iphone13pro')],
  ),
  Product(
    id: 'mock-2',
    sellerId: 'mock-seller',
    categoryId: 'cat-electro',
    categoryName: 'Electrónica',
    title: 'PlayStation 5 + 2 controles + 4 juegos',
    description:
        'PS5 en perfecto estado. Incluye 2 DualSense, God of War Ragnarök, Spider-Man 2, FIFA 24 y Horizon.',
    price: 520.00,
    isNegotiable: true,
    condition: ProductCondition.buenEstado,
    status: ProductStatus.active,
    brand: 'Sony',
    createdAt: DateTime.now().subtract(const Duration(hours: 5)),
    updatedAt: DateTime.now(),
    sellerName: 'María G.',
    sellerTrustScore: 88,
    images: [_img('mock-2', 'ps5gaming')],
  ),
  Product(
    id: 'mock-3',
    sellerId: 'mock-seller',
    categoryId: 'cat-electro',
    categoryName: 'Electrónica',
    title: 'MacBook Air M1 8GB 256GB',
    description:
        'Muy buen estado. Batería al 88%, sin daños físicos. macOS Sonoma instalado.',
    price: 650.00,
    isNegotiable: true,
    condition: ProductCondition.buenEstado,
    status: ProductStatus.active,
    brand: 'Apple',
    createdAt: DateTime.now().subtract(const Duration(hours: 8)),
    updatedAt: DateTime.now(),
    sellerName: 'Pedro A.',
    sellerTrustScore: 95,
    images: [_img('mock-3', 'macbookair')],
  ),
  Product(
    id: 'mock-4',
    sellerId: 'mock-seller',
    categoryId: 'cat-ropa',
    categoryName: 'Ropa y Accesorios',
    title: 'Chaqueta North Face – talla M',
    description:
        'Impermeable, usada 3 veces. Color negro. Perfecta para clima frío.',
    price: 85.00,
    isNegotiable: false,
    condition: ProductCondition.comoNuevo,
    status: ProductStatus.active,
    brand: 'The North Face',
    createdAt: DateTime.now().subtract(const Duration(hours: 10)),
    updatedAt: DateTime.now(),
    sellerName: 'Ana R.',
    sellerTrustScore: 80,
    images: [_img('mock-4', 'northfacejacket')],
  ),
  Product(
    id: 'mock-5',
    sellerId: 'mock-seller',
    categoryId: 'cat-ropa',
    categoryName: 'Ropa y Accesorios',
    title: 'Nike Air Jordan 1 – talla 42',
    description:
        'Colorway Chicago. Usados 5 veces con mucho cuidado. Con caja original.',
    price: 170.00,
    isNegotiable: false,
    condition: ProductCondition.buenEstado,
    status: ProductStatus.active,
    brand: 'Nike',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    updatedAt: DateTime.now(),
    sellerName: 'Luis F.',
    sellerTrustScore: 75,
    images: [_img('mock-5', 'airjordan1')],
  ),
  Product(
    id: 'mock-6',
    sellerId: 'mock-seller',
    categoryId: 'cat-dep',
    categoryName: 'Deportes',
    title: 'Bicicleta Trek 21 velocidades',
    description:
        'Aro 26, buen estado. Cambios y frenos funcionando. Llantas casi nuevas.',
    price: 150.00,
    isNegotiable: true,
    condition: ProductCondition.buenEstado,
    status: ProductStatus.active,
    brand: 'Trek',
    createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
    updatedAt: DateTime.now(),
    sellerName: 'Sofía T.',
    sellerTrustScore: 85,
    images: [_img('mock-6', 'mountainbike')],
  ),
  Product(
    id: 'mock-7',
    sellerId: 'mock-seller',
    categoryId: 'cat-dep',
    categoryName: 'Deportes',
    title: 'Pesas ajustables 2-24kg Bowflex',
    description:
        'Sistema de dial para ajustar peso en segundos. Casi sin uso. Perfectas para gym en casa.',
    price: 180.00,
    isNegotiable: false,
    condition: ProductCondition.comoNuevo,
    status: ProductStatus.active,
    brand: 'Bowflex',
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
    updatedAt: DateTime.now(),
    sellerName: 'Diego V.',
    sellerTrustScore: 90,
    images: [_img('mock-7', 'dumbbells')],
  ),
  Product(
    id: 'mock-8',
    sellerId: 'mock-seller',
    categoryId: 'cat-hogar',
    categoryName: 'Hogar y Muebles',
    title: 'Mesa comedor madera – 6 puestos',
    description:
        '160x90 cm. Madera maciza, muy buen estado. Pequeños detalles de uso. Sin sillas.',
    price: 200.00,
    isNegotiable: true,
    condition: ProductCondition.buenEstado,
    status: ProductStatus.active,
    brand: null,
    createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 5)),
    updatedAt: DateTime.now(),
    sellerName: 'Laura P.',
    sellerTrustScore: 78,
    images: [_img('mock-8', 'woodtable')],
  ),
  Product(
    id: 'mock-9',
    sellerId: 'mock-seller',
    categoryId: 'cat-electro',
    categoryName: 'Electrónica',
    title: 'Sony a6400 + lente 16-50mm',
    description:
        'Solo 8000 disparos. Batería extra, cargador y correa original. Perfecta para fotos y video.',
    price: 750.00,
    isNegotiable: true,
    condition: ProductCondition.buenEstado,
    status: ProductStatus.active,
    brand: 'Sony',
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
    updatedAt: DateTime.now(),
    sellerName: 'Roberto C.',
    sellerTrustScore: 93,
    images: [_img('mock-9', 'sonycamera')],
  ),
  Product(
    id: 'mock-10',
    sellerId: 'mock-seller',
    categoryId: 'cat-libros',
    categoryName: 'Libros y Juegos',
    title: 'Harry Potter – 7 tomos pasta dura',
    description:
        'Colección completa en español. Pasta dura, buen estado con algunas marcas de lectura.',
    price: 45.00,
    isNegotiable: true,
    condition: ProductCondition.buenEstado,
    status: ProductStatus.active,
    brand: null,
    createdAt: DateTime.now().subtract(const Duration(days: 4)),
    updatedAt: DateTime.now(),
    sellerName: 'Valentina S.',
    sellerTrustScore: 82,
    images: [_img('mock-10', 'harrypotterbooks')],
  ),
];
